// Bundles content/skills/*.md (Garrett's Local SEO Skills) into a TS module so
// the playbooks ship inside every serverless function without filesystem reads.
// Runs automatically before dev, build, typecheck, and test.
//
//   node --experimental-strip-types scripts/build-playbooks.ts
//
// To refresh from a skills folder first:
//   node --experimental-strip-types scripts/build-playbooks.ts --from /path/to/skills

import { copyFileSync, existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = "content/skills";
const OUT = "lib/garrett/playbooks.generated.ts";

const from = process.argv.indexOf("--from");
if (from !== -1) {
  const src = process.argv[from + 1];
  for (const f of readdirSync(DIR).filter((f) => f.endsWith(".md") && f !== "README.md")) {
    const skill = join(src, f.replace(/\.md$/, ""), "SKILL.md");
    if (existsSync(skill)) {
      copyFileSync(skill, join(DIR, f));
      console.log(`refreshed ${f}`);
    } else {
      console.warn(`missing in source, kept local copy: ${f}`);
    }
  }
}

type Playbook = { name: string; description: string; body: string };
const playbooks: Playbook[] = [];

for (const f of readdirSync(DIR).filter((f) => f.endsWith(".md") && f !== "README.md").sort()) {
  const raw = readFileSync(join(DIR, f), "utf8");
  const fm = raw.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!fm) throw new Error(`${f}: missing frontmatter`);
  const field = (k: string) => {
    const m = fm[1].match(new RegExp(`^${k}:\\s*(.*)$`, "m"));
    if (!m) throw new Error(`${f}: missing ${k}`);
    const v = m[1].trim();
    return v.startsWith('"') ? (JSON.parse(v) as string) : v;
  };
  playbooks.push({ name: field("name"), description: field("description"), body: raw.slice(fm[0].length).trim() });
}

writeFileSync(
  OUT,
  `// GENERATED by scripts/build-playbooks.ts from content/skills. Do not edit.\n` +
    `export const PLAYBOOKS: ReadonlyArray<{ name: string; description: string; body: string }> = ${JSON.stringify(playbooks, null, 2)};\n`,
);
console.log(`wrote ${playbooks.length} playbooks to ${OUT}`);
